### ISSUE TITLE
upload binaries for easy testing

### ISSUE THREAD

**Issue by mayermakes** [hpsaturn/esp32s3-linux#1]
I tried to compile with the original method and your docker version. my computer fataly crashes when it hits the step building gcc.
it would be helpfull to just provide the finished binaries in the repo so we can quickly flash them to our hardware to try out linux on esp32s3.
thanks.

TL:DR: please upload the resulting binaries to the repo.

**Comment by hpsaturn** [comment]
Thanks for your comment. It is ready:

[![screenshot20230901_224942](https://github.com/hpsaturn/esp32s3-linux/assets/423856/4e4154d7-8c16-4247-8099-679d13ad7d8a)](https://github.com/hpsaturn/esp32s3-linux/releases)

**Comment by mayermakes** [comment]
thank you very much!
