### ISSUE TITLE
etc partition

### ISSUE THREAD

**Issue by BrunoAgst** [hpsaturn/esp32s3-linux#3]
Hi,

I'm getting error FileNotFoundError build-buildroot-esp32s3/images/etc.jffs2.

Would you help me?

**Comment by hpsaturn** [comment]
well, I think that maybe we need sync the recipe of the Docker to the last version. The key should be here:
https://github.com/jcmvbkbc/esp32-linux-build
and also because I already have this partition but in my Debian build environment without docker, in my local machine..

**Comment by hpsaturn** [comment]
Please paste here the console output of the error, to understand when happen. Thanks

**Comment by hpsaturn** [comment]
Hi Bruno, if you did found a issue in the DockerFile please submit the fix. Thanks
