### ISSUE TITLE
Read only filesystem

### ISSUE THREAD

**Issue by Mate1980** [hpsaturn/esp32s3-linux#5]
Hi!

I'm trying to connect to a wifi network, but when i try to save the wpa_supplicant.conf file, it says that the filesystem is read-only. What am i doing wrong?

**Comment by mayermakes** [comment]
only the /etc directory is writeable you need to make your changes there:
check out to this video (timestamped):
https://youtu.be/pj0a91vlcGo?si=zm1FPbjVRwlcYLMc&t=930
you need to edit the wpa_supplicant.conf  file present in this directory. 
BUT: it could also be that you flashed one of the older versions that is fully write protected.
quickly checkable by trying to write to /etc

**Comment by Mate1980** [comment]
Yes, it was an older version. Thanks!

**Comment by mayermakes** [comment]
@hpsaturn this one can be closed.
