### ISSUE TITLE
big chunky error

### ISSUE THREAD

**Issue by TheRegularDX** [hpsaturn/esp32s3-linux#8]
i was building the dockerfile and after a while this error pops up 
![image](https://github.com/hpsaturn/esp32s3-linux/assets/70165606/1a63429e-d839-45f4-8668-7611dc73957c)

im building it on ubuntu WSL

**Comment by hpsaturn** [comment]
Please check the last version and its instructions. I fixed a lot of issues and procedure is more simple. Please give me feedback from any issue. Thanks!

**Comment by TheRegularDX** [comment]
aw thanks! will try tomorrow
